# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
username: "juan" # < TU_USUARIO@hodl.ar

# NOSTR Settings
nostr:
  npub: "npub1kce2jpe7svm6y2yknart4k4vd6cqxh22fcy06d7gyd2ayc64nggsw5r9z7"

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Juan José # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#0d1117"
  cover_color: "#16b22"

# Configuración Central
main:
  title: Juan José # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

#  - title: Instagram
#    icon: instagram
#    url: https://www.instagram.com/lacryptaok/

  - title: Github
    icon: github
    url: https://github.com/jjramirezn
  - title: LinkedIn # Este es el nombre del botón
    icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
    url: https://www.linkedin.com/in/jramireznieves/ # Link a donde redireccionará al hacer click
  - title: Nostr
    icon: nostr
    url: https://snort.social/p/npub1kce2jpe7svm6y2yknart4k4vd6cqxh22fcy06d7gyd2ayc64nggsw5r9z7
  - title: Twitter
    icon: twitter
    url: https://twitter.com/JuanJoseBTC

# - title: Sitio Web
#   icon: url
#   url: https://www.TU-WEB.com

# - title: Telegram
#   icon: telegram
#   url: https://t.me/TU-USUARIO
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
